# "desktop/prebuilt/cartoon/BUILD"
# https://github.com/61315/mediapipe-prebuilt/tree/master/src/desktop/cartoon

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "cartoon_gan_cpu",
    deps = [
        "//mediapipe/examples/desktop/prebuilt:prebuilt_run_graph_main_cpu",
        "//mediapipe/examples/desktop/prebuilt/cartoon/graphs:desktop_live_calculators",
    ],
)