# "ios/prebuilt/facades/models/BUILD"
# https://github.com/61315/mediapipe-prebuilt/tree/master/src/ios/facades

package(default_visibility = ["//visibility:public"])

exports_files(
    srcs = glob(["**"]),
)
